// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhMh5bWu7maLe9tNLqK9DvdsmUFibUNl8',
    appId: '1:309972626596:web:5a4779b6f632c341454a31',
    messagingSenderId: '309972626596',
    projectId: 'mefe-spor-okulu-2026',
    authDomain: 'mefe-spor-okulu-2026.firebaseapp.com',
    storageBucket: 'mefe-spor-okulu-2026.firebasestorage.app',
    measurementId: 'G-MY5Z111MQS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYIFCR3bN8NeF_fIW5QopWn-Alx0x4hVc',
    appId: '1:309972626596:ios:2ca158809c660b4e454a31',
    messagingSenderId: '309972626596',
    projectId: 'mefe-spor-okulu-2026',
    storageBucket: 'mefe-spor-okulu-2026.firebasestorage.app',
    iosBundleId: 'com.mefepalta.sporokulu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhMh5bWu7maLe9tNLqK9DvdsmUFibUNl8',
    appId: '1:309972626596:web:3390b7ead0c5ba51454a31',
    messagingSenderId: '309972626596',
    projectId: 'mefe-spor-okulu-2026',
    authDomain: 'mefe-spor-okulu-2026.firebaseapp.com',
    storageBucket: 'mefe-spor-okulu-2026.firebasestorage.app',
    measurementId: 'G-KJL9W16YM0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYIFCR3bN8NeF_fIW5QopWn-Alx0x4hVc',
    appId: '1:309972626596:ios:5422405617c96534454a31',
    messagingSenderId: '309972626596',
    projectId: 'mefe-spor-okulu-2026',
    storageBucket: 'mefe-spor-okulu-2026.firebasestorage.app',
    iosBundleId: 'com.mefepalta.sporokulu',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY09tVEeS_SJTL3EjNOLPCvvocFVlNsgQ',
    appId: '1:309972626596:android:49263c22eee50725454a31',
    messagingSenderId: '309972626596',
    projectId: 'mefe-spor-okulu-2026',
    storageBucket: 'mefe-spor-okulu-2026.firebasestorage.app',
  );
}
